openapi: 3.0.0

info:
  title: Scanner Badge API
  version: 1.0.0
  description: API de gestion des employés et chantiers

servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:

  /auth/register:
    post:
      tags:
        - Auth
      summary: Inscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Utilisateur créé

  /auth/login:
    post:
      tags:
        - Auth
      summary: Connexion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Connexion réussie

  /chantiers:
    get:
      tags:
        - Chantiers
      summary: Liste des chantiers
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK

    post:
      tags:
        - Chantiers
      summary: Créer un chantier
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Créé

  /chantiers/{id}:
    get:
      tags:
        - Chantiers
      summary: Obtenir un chantier
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK

    put:
      tags:
        - Chantiers
      summary: Modifier un chantier
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Modifié

    delete:
      tags:
        - Chantiers
      summary: Supprimer un chantier
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Supprimé

  /employe:
    get:
      tags:
        - Employes
      summary: Liste des employés
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK

    post:
      tags:
        - Employes
      summary: Créer un employé
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Créé

  /employe/{id}:
    get:
      tags:
        - Employes
      summary: Obtenir un employé
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK

    put:
      tags:
        - Employes
      summary: Modifier un employé
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Modifié

    delete:
      tags:
        - Employes
      summary: Supprimer un employé
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Supprimé
  /geofencing/check:
    post:
      tags:
        - Geofencing
      summary: Vérifier si un employé est dans la zone du chantier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - employeeLat
                - employeeLon
                - chantierLat
                - chantierLon
                - radius
              properties:
                employeeLat:
                  type: number
                  example: 48.8566
                employeeLon:
                  type: number
                  example: 2.3522
                chantierLat:
                  type: number
                  example: 48.8567
                chantierLon:
                  type: number
                  example: 2.3523
                radius:
                  type: number
                  example: 100
      responses:
        "200":
          description: Résultat du contrôle géographique
          content:
            application/json:
              schema:
                type: object
                properties:
                  distance:
                    type: number
                    example: 13.3
                  inside:
                    type: boolean
                    example: true

  /badges/associate:
    post:
      tags:
        - Badges
      summary: Associer un badge RFID à un employé
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - uid
                - employeId
              properties:
                uid:
                  type: string
                  example: A1B2C3D4
                employeId:
                  type: string
                  example: 8790f88e-38c9-40ea-b648-09eafe46d86e
      responses:
        "201":
          description: Badge associé avec succès
        "400":
          description: Badge déjà associé ou employé possède déjà un badge

  /badges/{uid}/employe:
    get:
      tags:
        - Badges
      summary: Récupérer l'employé associé à un badge RFID
      parameters:
        - name: uid
          in: path
          required: true
          description: UID du badge RFID
          schema:
            type: string
            example: A1B2C3D4
      responses:
        "200":
          description: Employé trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  nom:
                    type: string
                  prenom:
                    type: string
        "404":
          description: Badge introuvable          